name: Docker

on:
  push:
    # Publish `$default-branch` as Docker `latest` image.
    branches:
      - zihaoyu/docker

    # Publish `v1.2.3` tags as releases.
    #tags:
    #  - v*

env:
  IMAGE_NAME: 971383676178.dkr.ecr.us-west-2.amazonaws.com/apib2swagger:latest

jobs:
  # Run tests.
  # See also https://docs.docker.com/docker-hub/builds/automated-testing/
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run tests
        run: |
          if [ -f docker-compose.test.yml ]; then
            docker-compose --file docker-compose.test.yml build
            docker-compose --file docker-compose.test.yml run sut
          else
            docker build . --file Dockerfile
          fi

  push:
    # Ensure build-and-test job passes before pushing image.
    needs: build-and-test

    runs-on: ubuntu-latest
    # if: github.event_name == 'push'

    steps:
      - uses: actions/checkout@v2

      - name: Build image
        run: docker build . --file Dockerfile --tag $IMAGE_NAME

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@8eba69932f928f2bc1b9837d16a095e7e1cb0845
        with:
          aws-region: us-west-2
          role-to-assume: arn:aws:iam::971383676178:role/gha-role-ecr-push-hbogo

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1

      - name: Push image to Amazon ECR
        run: docker push $IMAGE_NAME
